spring:
  application:
    name: api-gateway
  config:
    import:
    - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: default
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka