spring:
  application:
    name: relationship-management
  profiles:
    active:
    - dev
  cloud:
    config:
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
relationship.testedby.label: Tested By changed
      